# Generated by Django 4.2.11 on 2024-04-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='QuanLyThuChi_app.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='userCategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='QuanLyThuChi_app.usercategory'),
        ),
    ]
