# Generated by Django 4.2.11 on 2024-04-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['amount']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['amount']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='expenseCategory',
            field=models.ForeignKey(on_delete=models.SET('Không có'), related_name='expense', to='QuanLyThuChi_app.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='income',
            name='incomeCategory',
            field=models.ForeignKey(on_delete=models.SET('Không có'), related_name='income', to='QuanLyThuChi_app.incomecategory'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user/%Y/%m/%d/'),
        ),
    ]
