# Generated by Django 4.2.11 on 2024-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyThuChi_app', '0033_alter_transactioncategorygroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
